### ISSUE TITLE
Uploading to S3 is broken

### ISSUE THREAD

**Issue by philipmw** [SeanRoy/lambduh-maven-plugin#15]
Commit d01e78ac1359566603db43f63a66a252fc881dc3 broke uploading to S3. Now, when the file is not in S3 or its hash is different, the plugin raises this exception:

    [ERROR] The Content-MD5 you specified was invalid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidDigest; Request ID: 6D82591B56A1FAC9)

**Comment by SeanRoy** [comment]
I was getting this error when I tested your changes.  That's the reason I removed line 197.  The content-md5 metatag needs to be Base 64 encoded before it was uploaded.  Besides, you're using the E-Tag to verify the contents of the package, so setting the content md5 meta tag doesn't actually do anything.

It looks like you may not have the latest plugin or are using your original version cached locally in .m2.   I just ran my test project using the 1.0.5 version and it ran fine.

**Comment by SeanRoy** [comment]
Please try cleaning lambduh out of your .m2 directory and give it another go.

**Comment by SeanRoy** [comment]
Can I close this issue, or are you still seeing the error?

**Comment by philipmw** [comment]
My bad. The problem was that every time I do `mvn package`, the JAR has a different hash! Sorry for the false alarm. Cheers.
